# default_platform(:ios)

# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     increment_build_number(xcodeproj: "fastlane.xcodeproj")
#     build_app(workspace: "fastlane.xcworkspace", scheme: "fastlane")
#     upload_to_testflight
#   end
# end

before_all do
  ensure_git_branch(branch: 'main')
  ensure_git_status_clean
  git_pull
end

platform :ios do
  lane :certs do
    match(app_identifier: "com.onerivet.curamei", type: 'appstore', readonly: true)
  end

  private_lane :build do
    app_store_connect_api_key(
      key_id: "QBFWSPJBVY",
      issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
      key_filepath: "/Users/cs24-macmini/Desktop/ReactNative/certificates/SignInwithAppleCuramei_AuthKey_QBFWSPJBVY.p8",
    )

    certs
    increment_build_number(xcodeproj: "fastlane.xcodeproj")
    build_app(scheme: "fastlane", workspace: "fastlane.xcworkspace", configuration: 'Release')
  end

  lane :distribute do
    build
    pilot
    commit_version_bump(message: "Version bump", xcodeproj: "fastlane.xcodeproj")
    push_to_git_remote
  end
end
